import 'dart:developer';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:cloud_functions/cloud_functions.dart';
import 'package:connecto/feature/circles/models/circle_model.dart';
import 'package:connecto/feature/circles/models/group_message_model.dart';
import 'package:connecto/feature/circles/widgets/event_message_card.dart';
import 'package:connecto/feature/dashboard/screens/bonds_screen.dart';
import 'package:connecto/feature/gatherings/models/gathering_model.dart';
import 'package:connecto/feature/pings/model/ping_model.dart';
import 'package:connecto/feature/pings/screens/ping_list_screen.dart';
import 'package:connecto/feature/pings/widgets/ping_visualizer_chat.dart';
import 'package:connecto/feature/poll/widgets/poll_message_card.dart';
import 'package:connecto/helper/color_helper.dart';
import 'package:connecto/main.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:intl/intl.dart';

final circleGatheringsProvider =
    StreamProvider.family<List<GatheringModel>, String>((ref, circleId) {
  return FirebaseFirestore.instance
      .collection('gatherings')
      .where('circleId', isEqualTo: circleId)
      .snapshots()
      .map((snapshot) =>
          snapshot.docs.map((doc) => GatheringModel.fromDoc(doc)).toList());
});

class GroupPingChatScreen extends ConsumerWidget {
  final String circleId;

  final CircleModel circle;

  const GroupPingChatScreen(
      {super.key, required this.circleId, required this.circle});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final circleId = circle.id;
    final gatheringListAsync = ref.watch(circleGatheringsProvider(circleId));

    // Clear new message flag when user opens the group chat
    Future<void> clearGroupChatFlag({
      required String circleId,
      required String userId,
    }) async {
      final flagRef = FirebaseFirestore.instance
          .collection('users')
          .doc(userId)
          .collection('groupChatFlags')
          .doc(circleId);

      await flagRef.update({'hasNewMessage': false});
    }

    final ScrollController _scrollController = ScrollController();
    final currentUser = FirebaseAuth.instance.currentUser!.uid;

    final currentUserAsync = ref.read(currentUserProvider);

    void _scrollToBottom() {
      Future.delayed(Duration(milliseconds: 10), () {
        if (_scrollController.hasClients) {
          _scrollController.jumpTo(_scrollController.position.maxScrollExtent);
        }
      });
    }

    Future<void> updateGroupChatFlagsForNewMessage(
        String circleId, String senderId) async {
      final firestore = FirebaseFirestore.instance;

      // Fetch the circle to get all registered users
      final circleSnapshot =
          await firestore.collection('circles').doc(circleId).get();

      if (!circleSnapshot.exists) return;

      final data = circleSnapshot.data();
      final List<dynamic> registeredUsers = data?['registeredUsers'] ?? [];

      // Loop through users and set flag
      for (final userId in registeredUsers) {
        if (userId != senderId) {
          await firestore
              .collection('users')
              .doc(userId)
              .collection('groupChatFlags')
              .doc(circleId)
              .set({
            'hasNewMessage': true,
            'lastUpdated': FieldValue.serverTimestamp(),
          }, SetOptions(merge: true));
        }
      }
    }

    final messagesStream = FirebaseFirestore.instance
        .collection('groupChats')
        .doc(circleId)
        .collection('messages')
        .orderBy('timestamp', descending: false)
        .snapshots();

    Future<void> sendPingToGroup(PingModel ping) async {
      final messageRef = FirebaseFirestore.instance
          .collection('groupChats')
          .doc(circleId)
          .collection('messages')
          .doc();

      final user = FirebaseAuth.instance.currentUser!;

      await messageRef.set({
        'messageId': messageRef.id,
        'senderId': user.uid,
        'senderName': currentUserAsync.value!.fullName,
        'text': ping.name,
        'timestamp': FieldValue.serverTimestamp(),
        'isAutoGenerated': false,
        'pingPattern': ping.pattern,
      });

      await FirebaseFirestore.instance
          .collection('groupChats')
          .doc(circleId)
          .update({
        'lastMessage': {
          'text': ping.name,
          'timestamp': FieldValue.serverTimestamp(),
          'senderId': user.uid,
        }
      });

      await FirebaseFunctions.instance
          .httpsCallable('sendGroupPingNotification')
          .call({
        "circleId": circleId,
        "messageText": ping.name,
        "senderId": currentUser,
        "senderName": currentUserAsync.value!.fullName,
        "vibrationPattern":
            ping.pattern.join(','), // 👈 make sure it's a string
      });

      // ✅ Set flag for others
      await updateGroupChatFlagsForNewMessage(circleId, user.uid);
    }

    // ✅ Clear the hasNewMessage flag when screen opens
    Future.microtask(() async {
      await clearGroupChatFlag(circleId: circleId, userId: currentUser);
    });
    return Scaffold(
      backgroundColor: const Color(0xff001311),
      appBar: PreferredSize(
        preferredSize: Size.fromHeight(100), // ✅ Set custom height
        child: Container(
          padding: EdgeInsets.only(
              top: MediaQuery.of(context).padding.top), // Status bar safe area
          decoration: BoxDecoration(
            color: Color(0xff091F1E), // ✅ Background color matching the design
            borderRadius: BorderRadius.vertical(
              bottom: Radius.circular(10), // ✅ Optional rounded bottom
            ),
          ),
          child: Padding(
            padding: EdgeInsets.symmetric(horizontal: 0, vertical: 10),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                // 🔙 Back Button
                IconButton(
                  icon: Icon(Icons.arrow_back, color: Colors.white),
                  onPressed: () => context.pop(),
                ),
                // Spacer(flex: 1,),

                // Friend Name & Online Status
                Column(
                  crossAxisAlignment: CrossAxisAlignment.center,
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    // 📸 Profile Picture + Name
                    CircleAvatar(
                      radius: 18,
                      backgroundColor: hexToColor(circle.circleColor),
                      child: Icon(Icons.groups, color: Colors.white),
                    ),
                    SizedBox(height: 6),
                    Text(
                      circle.circleName,
                      style: TextStyle(
                        color: Colors.white,
                        fontSize: 16,
                        fontWeight: FontWeight.w600,
                      ),
                    ),
                  ],
                ),
                TextButton(
                  onPressed: () {},
                  child: Text("Add",
                      style:
                          TextStyle(color: Colors.transparent, fontSize: 16)),
                ),
                // Spacer(flex: 2,)
              ],
            ),
          ),
        ),
      ),
      body: Column(
        children: [
          gatheringListAsync.when(
            data: (gatherings) {
              final now = DateTime.now();
              final upcoming =
                  gatherings.where((g) => g.dateTime.isAfter(now)).toList();

              if (upcoming.isEmpty) return SizedBox();

              return Column(
                children: upcoming.map((gathering) {
                  final timeFormatted = DateFormat('hh:mm a - dd MMM yyyy')
                      .format(gathering.dateTime);

                  final text =
                      "You have a group gathering for ${gathering.eventType}";

                  return GestureDetector(
                    onTap: () {
                      context.push(
                          '/gathering/gathering-details/${gathering.id}',
                          extra: gathering);
                    },
                    child: Container(
                      margin: EdgeInsets.only(bottom: 6),
                      padding: const EdgeInsets.all(16),
                      decoration: BoxDecoration(
                        color: Color(0xff091F1E),
                        border: Border.symmetric(
                          horizontal: BorderSide(
                              color: Colors.grey.shade700, width: 0.5),
                        ),
                      ),
                      child: Row(
                        children: [
                          Icon(Icons.group, color: Colors.white),
                          const SizedBox(width: 12),
                          Expanded(
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Text(text,
                                    style: TextStyle(
                                        color: Colors.white,
                                        fontSize: 14,
                                        fontWeight: FontWeight.w500)),
                                const SizedBox(height: 4),
                                Text(timeFormatted,
                                    style: TextStyle(
                                        color: Colors.grey, fontSize: 13)),
                              ],
                            ),
                          ),
                          Icon(Icons.arrow_forward, color: Colors.tealAccent)
                        ],
                      ),
                    ),
                  );
                }).toList(),
              );
            },
            loading: () => SizedBox(),
            error: (_, __) => SizedBox(),
          ),

          Expanded(
            child: StreamBuilder<QuerySnapshot>(
              stream: messagesStream,
              builder: (context, snapshot) {
                if (!snapshot.hasData) {
                  return const Center(child: CircularProgressIndicator());
                }

                final docs = snapshot.data!.docs;
                WidgetsBinding.instance.addPostFrameCallback((_) {
                  _scrollToBottom();
                });

                log('docs length : ${docs.length}');

                return ListView.builder(
                  controller: _scrollController,
                  padding: const EdgeInsets.all(16),
                  itemCount: docs.length,
                  itemBuilder: (context, index) {
                    final doc = docs[index];
                    final message = GroupMessageModel.fromFirestore(doc);

                    log('message : ${message.id}');

                    final isMine = message.senderId == currentUser;

                    // 🔁 NEW: Show event card message
                    if (message.type == 'event') {
                      return Align(
                        alignment: isMine
                            ? Alignment.centerRight
                            : Alignment.centerLeft,
                        child: Padding(
                          padding: const EdgeInsets.only(bottom: 20),
                          child: Column(
                            crossAxisAlignment: isMine
                                ? CrossAxisAlignment.end
                                : CrossAxisAlignment.start,
                            children: [
                              EventMessageCard(
                                message: message,
                                isMine: isMine,
                              ),
                              Text(
                                DateFormat('hh:mm a').format(message.timestamp),
                                style: const TextStyle(
                                    fontSize: 12, color: Colors.grey),
                              ),
                            ],
                          ),
                        ),
                      );
                    }

                    // inside itemBuilder:
                    if (message.type == 'poll') {
                      // Make sure your GroupMessageModel exposes pollId, text (title), etc.
                      return Align(
                        alignment: isMine
                            ? Alignment.centerRight
                            : Alignment.centerLeft,
                        child: Padding(
                          padding: const EdgeInsets.only(bottom: 20),
                          child: Column(
                            crossAxisAlignment: isMine
                                ? CrossAxisAlignment.end
                                : CrossAxisAlignment.start,
                            children: [
                              PollMessageCard(
                                circleId: circleId,
                                pollId: message
                                    .pollId!, // add this field to your model
                                isMine: isMine,
                                headerText: message.text, // optional
                              ),
                              Text(
                                DateFormat('hh:mm a').format(message.timestamp),
                                style: const TextStyle(
                                    fontSize: 12, color: Colors.grey),
                              ),
                            ],
                          ),
                        ),
                      );
                    }

                    return Align(
                      alignment:
                          isMine ? Alignment.centerRight : Alignment.centerLeft,
                      child: Container(
                        constraints: BoxConstraints(
                          maxWidth: MediaQuery.sizeOf(context).width *
                              0.5, // ✅ Max 75% of screen width
                          minWidth: 60, // ✅ Minimum width to avoid collapse
                        ),
                        child: Padding(
                          padding: const EdgeInsets.only(bottom: 20),
                          child: Column(
                            crossAxisAlignment: isMine
                                ? CrossAxisAlignment.end
                                : CrossAxisAlignment.start,
                            children: [
                              if (!isMine)
                                Text(
                                  message.senderName,
                                  style: const TextStyle(
                                      fontSize: 12, color: Colors.grey),
                                ),
                              Container(
                                padding: const EdgeInsets.symmetric(
                                    horizontal: 14, vertical: 12),
                                decoration: BoxDecoration(
                                  color: isMine
                                      ? const Color(0xff0C6353)
                                      : const Color(0xff091F1E),
                                  borderRadius: BorderRadius.circular(10),
                                ),
                                child: Column(
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Text(
                                      message.text,
                                      style: const TextStyle(
                                          color: Colors.white, fontSize: 16),
                                    ),
                                    if (message.pingPattern.isNotEmpty)
                                      Padding(
                                        padding: const EdgeInsets.only(top: 6),
                                        child: PingVisualizerChat(
                                            pattern: message.pingPattern),
                                      ),
                                  ],
                                ),
                              ),
                              Text(
                                DateFormat('hh:mm a').format(message.timestamp),
                                style: const TextStyle(
                                    fontSize: 12, color: Colors.grey),
                              ),
                            ],
                          ),
                        ),
                      ),
                    );
                  },
                );
              },
            ),
          ),
          // 🔽 Bottom Buttons
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 12),
            child: Row(
              children: [
                Expanded(
                  child: _bottomActionButton(
                    icon: Icons.emoji_emotions_outlined,
                    label: "Send Ping",
                    onTap: () async {
                      PingModel? selectedPing =
                          await showModalBottomSheet<PingModel>(
                        context: context,
                        isScrollControlled: true,
                        backgroundColor: Colors.transparent,
                        builder: (context) =>
                            PingListModal(pings: predefinedPings),
                      );

                      if (selectedPing != null) {
                        sendPingToGroup(selectedPing);
                      }
                    },
                  ),
                ),
                const SizedBox(width: 10),
                Expanded(
                  child: _bottomActionButton(
                    icon: Icons.hourglass_empty,
                    label: "Create Gathering",
                    onTap: () {
                      context.push(
                        '/gathering/create-gathering-circle',
                        extra: {
                          'circleId': circleId,

                          'registeredUsers':
                              circle.registeredUsers, // List<UserModel>?
                          'unregisteredUsers': circle.unregisteredUsers,
                        },
                      );
                    },
                  ),
                ),
                const SizedBox(width: 10),
                Expanded(
                  child: _bottomActionButton(
                    icon: Icons.poll,
                    label: "Create Poll",
                    onTap: () {
                      context.push(
                        '/gathering/create-poll',
                        extra: {
                          'circleId': circleId,
                        },
                      );
                    },
                  ),
                ),
              ],
            ),
          ),
          const SizedBox(height: 30)
        ],
      ),
    );
  }

  Widget _bottomActionButton({
    required IconData icon,
    required String label,
    required VoidCallback onTap,
  }) {
    return InkWell(
      onTap: onTap,
      child: Container(
        height: 99,
        padding: const EdgeInsets.symmetric(vertical: 14),
        decoration: BoxDecoration(
          color: const Color(0xff082523),
          borderRadius: BorderRadius.circular(12),
        ),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Icon(icon, size: 28, color: const Color(0xff03FFE2)),
            const SizedBox(height: 8),
            Text(label,
                style: const TextStyle(color: Colors.white, fontSize: 14)),
          ],
        ),
      ),
    );
  }
}
