import 'dart:developer';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:cloud_functions/cloud_functions.dart';
import 'package:connecto/feature/poll/models/poll_model.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

/// STREAM: single poll
final pollProvider =
    StreamProvider.family<Poll, ({String circleId, String pollId})>(
        (ref, ids) async* {
  final stream = FirebaseFirestore.instance
      .collection('circles')
      .doc(ids.circleId)
      .collection('polls')
      .doc(ids.pollId)
      .snapshots();

  await for (final s in stream) {
    if (s.exists) yield Poll.fromDoc(s);
  }
});

/// STREAM: current user's vote for a poll
final myVoteProvider = StreamProvider.family<PollVote?,
    ({String circleId, String pollId, String uid})>((ref, ids) async* {
  final stream = FirebaseFirestore.instance
      .collection('circles')
      .doc(ids.circleId)
      .collection('polls')
      .doc(ids.pollId)
      .collection('votes')
      .doc(ids.uid)
      .snapshots();

  await for (final s in stream) {
    if (s.exists) {
      yield PollVote.fromDoc(s);
    } else {
      yield null;
    }
  }
});

/// COMMANDS
class PollController extends StateNotifier<AsyncValue<void>> {
  PollController(this._ref) : super(const AsyncData(null));
  final Ref _ref;

  FirebaseFirestore get _db => FirebaseFirestore.instance;
  FirebaseAuth get _auth => FirebaseAuth.instance;

  /// Create a poll under /circles/{circleId}/polls and drop a 'poll' chat message.
  Future<String> createPoll({
    required String circleId,
    required String title,
    required String activity,
    required List<PollLocation> locations,
    required List<PollTimeSlot> timeSlots,
    required DateTime closesAt,
    required String senderName,
    // 👈 NEW
    double? minQuorum, // 👈 NEW (0..1) optional
  }) async {
    state = const AsyncLoading();

    // 🔽 fetch circle doc
    final circleSnap = await _db.collection('circles').doc(circleId).get();
    if (!circleSnap.exists) {
      throw Exception("Circle not found");
    }
    final circleData = circleSnap.data()!;
    final List<String> requiredVoters = (circleData['registeredUsers'] as List?)
            ?.map((e) => e.toString())
            .toList() ??
        [];
    final uid = _auth.currentUser!.uid;
    final pollsCol =
        _db.collection('circles').doc(circleId).collection('polls');
    final doc = pollsCol.doc();

    final poll = Poll(
      id: doc.id,
      circleId: circleId,
      title: title,
      activity: activity,
      createdBy: uid,
      createdAt: DateTime.now(),
      closesAt: closesAt,
      closedAt: null,
      status: PollStatus.open,
      locations: locations,
      timeSlots: timeSlots,
      countLocation: {for (final l in locations) l.id: 0},
      countTime: {for (final t in timeSlots) t.id: 0},
      requiredVoters: requiredVoters,
      minQuorum: minQuorum,
    );

    await doc.set(poll.toMap());

    // Create a "poll" message in group chat feed (✅ correct collection)
    final col =
        _db.collection('groupChats').doc(circleId).collection('messages');
    final ref = col.doc();

    await ref.set({
      'messageId': ref.id,
      'type': 'poll',
      'senderId': uid,
      'senderName': senderName,
      'text': title, // header for the bubble
      'timestamp': FieldValue.serverTimestamp(),
      'isAutoGenerated': false,
      'pingPattern': [],

      // poll-only
      'pollId': doc.id,
      'pollTitle': title,
      'pollStatus': 'open',
      'pollClosesAt': Timestamp.fromDate(closesAt),
    });

    // Optional: Update lastMessage
    await _db.collection('groupChats').doc(circleId).update({
      'lastMessage': {
        'text': 'Check out this poll!',
        'timestamp': FieldValue.serverTimestamp(),
        'senderId': uid,
      }
    });

    state = const AsyncData(null);
    return doc.id;
  }

  /// Cast/update a vote — client writes ONLY the vote doc. Server (CF) does counts & early-close.
  Future<void> vote({
    required String circleId,
    required String pollId,
    required String locationId,
    required String timeSlotId,
  }) async {
    final uid = _auth.currentUser!.uid;
    final voteRef = _db
        .collection('circles')
        .doc(circleId)
        .collection('polls')
        .doc(pollId)
        .collection('votes')
        .doc(uid);

    await voteRef.set(
      PollVote(
        locationId: locationId,
        timeSlotId: timeSlotId,
        votedAt: DateTime.now(),
      ).toMap(),
      SetOptions(merge: true),
    );
  }

  /// Manual close — creator triggers Cloud Function, server computes winners + updates chat.
  Future<void> closePoll({
    required String circleId,
    required String pollId,
  }) async {
    state = const AsyncLoading();
    try {
      final fn = FirebaseFunctions.instance.httpsCallable('closePollCallable');
      await fn.call({'circleId': circleId, 'pollId': pollId});
      state = const AsyncData(null);
    } catch (e, st) {
      log('closePoll error: $e\n$st');
      state = AsyncError(e, st);
    }
  }

  /// Optional: archive (hide from active lists)
  Future<void> archivePoll({
    required String circleId,
    required String pollId,
  }) async {
    await _db
        .collection('circles')
        .doc(circleId)
        .collection('polls')
        .doc(pollId)
        .update({'status': 'archived'});
  }
}

/// Expose controller
final pollControllerProvider =
    StateNotifierProvider<PollController, AsyncValue<void>>(
        (ref) => PollController(ref));
