import 'dart:developer';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:connecto/feature/poll/models/poll_model.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

/// STREAM: single poll
final pollProvider =
    StreamProvider.family<Poll, ({String circleId, String pollId})>(
        (ref, ids) async* {
  final stream = FirebaseFirestore.instance
      .collection('circles')
      .doc(ids.circleId)
      .collection('polls')
      .doc(ids.pollId)
      .snapshots();

  await for (final s in stream) {
    if (s.exists) yield Poll.fromDoc(s);
  }
});

/// STREAM: current user's vote for a poll
final myVoteProvider = StreamProvider.family<PollVote?,
    ({String circleId, String pollId, String uid})>((ref, ids) async* {
  final stream = FirebaseFirestore.instance
      .collection('circles')
      .doc(ids.circleId)
      .collection('polls')
      .doc(ids.pollId)
      .collection('votes')
      .doc(ids.uid)
      .snapshots();

  await for (final s in stream) {
    if (s.exists) {
      yield PollVote.fromDoc(s);
    } else {
      yield null;
    }
  }
});

/// COMMANDS
class PollController extends StateNotifier<AsyncValue<void>> {
  PollController(this._ref) : super(const AsyncData(null));
  final Ref _ref;

  FirebaseFirestore get _db => FirebaseFirestore.instance;
  FirebaseAuth get _auth => FirebaseAuth.instance;

  /// Create a poll under /circles/{circleId}/polls and drop a 'poll' chat message.
  Future<String> createPoll({
    required String circleId,
    required String title,
    required String activity,
    required List<PollLocation> locations,
    required List<PollTimeSlot> timeSlots,
    required DateTime closesAt,
    required String senderName
  }) async {
    state = const AsyncLoading();
    final uid = _auth.currentUser!.uid;
    final pollsCol =
        _db.collection('circles').doc(circleId).collection('polls');
    final doc = pollsCol.doc();

    final poll = Poll(
      id: doc.id,
      circleId: circleId,
      title: title,
      activity: activity,
      createdBy: uid,
      createdAt: DateTime.now(),
      closesAt: closesAt,
      status: PollStatus.open,
      locations: locations,
      timeSlots: timeSlots,
      countLocation: {for (final l in locations) l.id: 0},
      countTime: {for (final t in timeSlots) t.id: 0},
    );

    await doc.set(poll.toMap());

    // Optional: also create a "poll" message in circle chat feed
    // await _db.collection('groupChats').doc(circleId).collection('messages').add({
    //   'type': 'poll',
    //   'pollId': doc.id,
    //   'status': 'open',
    //   'text': 'Select your preferred location & time',
    //   'createdAt': FieldValue.serverTimestamp(),
    //   'createdBy': uid,
    // });

    // await _db
    //     .collection('groupChats')
    //     .doc(circleId) // circle/group id
    //     .collection('messages')
    //     .add({
    //   'type': 'poll',
    //   'pollId': doc.id,
    //   'status': 'open',
    //   'text': 'Select your preferred location & time',
    //   'createdAt': FieldValue.serverTimestamp(),
    //   'senderId': uid,
    // });

    final col = FirebaseFirestore.instance
        .collection('groupChats')
        .doc(circleId)
        .collection('messages');
    final ref = col.doc();

    await ref.set({
      'messageId': ref.id,
      'type': 'poll',
      'senderId': uid,
      'senderName': senderName,
      'text': title, // header for the bubble
      'timestamp': FieldValue.serverTimestamp(),
      'isAutoGenerated': false,
      'pingPattern': [],

      // poll-only
      'pollId': doc.id,
      'pollTitle': title,
      'pollStatus': 'open',
      'pollClosesAt': Timestamp.fromDate(closesAt),
    }, SetOptions(merge: false));
    // Optional: Update lastMessage
    await _db.collection('groupChats').doc(circleId).update({
      'lastMessage': {
        'text': 'Check out this poll!',
        'timestamp': FieldValue.serverTimestamp(),
        'senderId': uid,
      }
    });

    state = const AsyncData(null);
    return doc.id;
  }

  /// Cast/update a vote (transactionally adjusts counts).
  Future<void> vote({
    required String circleId,
    required String pollId,
    required String locationId,
    required String timeSlotId,
  }) async {
    final uid = _auth.currentUser!.uid;
    final pollRef =
        _db.collection('circles').doc(circleId).collection('polls').doc(pollId);
    final voteRef = pollRef.collection('votes').doc(uid);

    await _db.runTransaction((tx) async {
      final pollSnap = await tx.get(pollRef);
      if (!pollSnap.exists) throw Exception('Poll not found');

      // counts
      final data = pollSnap.data()!;
      final counts = Map<String, dynamic>.from(data['counts'] ?? {});
      final locCounts = Map<String, int>.from(counts['location'] ?? {});
      final timeCounts = Map<String, int>.from(counts['time'] ?? {});

      // previous?
      final prevSnap = await tx.get(voteRef);
      if (prevSnap.exists) {
        final pm = prevSnap.data()!;
        final prevLoc = pm['selectedLocationId'] as String?;
        final prevTime = pm['selectedTimeSlotId'] as String?;
        if (prevLoc != null && locCounts.containsKey(prevLoc)) {
          locCounts[prevLoc] = (locCounts[prevLoc]! - 1).clamp(0, 1 << 31);
        }
        if (prevTime != null && timeCounts.containsKey(prevTime)) {
          timeCounts[prevTime] = (timeCounts[prevTime]! - 1).clamp(0, 1 << 31);
        }
      }

      // increment new
      locCounts[locationId] = (locCounts[locationId] ?? 0) + 1;
      timeCounts[timeSlotId] = (timeCounts[timeSlotId] ?? 0) + 1;

      // write back
      tx.update(pollRef, {
        'counts.location': locCounts,
        'counts.time': timeCounts,
      });

      tx.set(
          voteRef,
          PollVote(
            locationId: locationId,
            timeSlotId: timeSlotId,
            votedAt: DateTime.now(),
          ).toMap());
    });
  }

  /// Close the poll — computes winners and updates chat message status.
  Future<void> closePoll({
    required String circleId,
    required String pollId,
  }) async {
    final uid = _auth.currentUser!.uid;
    final pollRef =
        _db.collection('circles').doc(circleId).collection('polls').doc(pollId);

    await _db.runTransaction((tx) async {
      final snap = await tx.get(pollRef);
      if (!snap.exists) return;
      final m = snap.data()!;
      if (m['createdBy'] != uid) return; // only creator can close

      final counts = Map<String, dynamic>.from(m['counts'] ?? {});
      final loc = Map<String, int>.from(counts['location'] ?? {});
      final tim = Map<String, int>.from(counts['time'] ?? {});

      String? locWin;
      String? timWin;

      if (loc.isNotEmpty) {
        locWin = loc.entries.reduce((a, b) => a.value >= b.value ? a : b).key;
      }
      if (tim.isNotEmpty) {
        timWin = tim.entries.reduce((a, b) => a.value >= b.value ? a : b).key;
      }

      tx.update(pollRef, {
        'status': 'closed',
        'winners.locationId': locWin,
        'winners.timeSlotId': timWin,
      });
    });

    // flip the chat message referencing this poll to 'closed'
    final msgs = await _db
        .collection('chats')
        .doc(circleId)
        .collection('messages')
        .where('pollId', isEqualTo: pollId)
        .limit(1)
        .get();
    if (msgs.docs.isNotEmpty) {
      await msgs.docs.first.reference.update({'status': 'closed'});
    }
  }

  /// Optional: archive (hide from active lists)
  Future<void> archivePoll({
    required String circleId,
    required String pollId,
  }) async {
    await _db
        .collection('circles')
        .doc(circleId)
        .collection('polls')
        .doc(pollId)
        .update({'status': 'archived'});
  }
}

/// Expose controller
final pollControllerProvider =
    StateNotifierProvider<PollController, AsyncValue<void>>(
        (ref) => PollController(ref));
