import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';

class GroupMessageModel {
  final String id;
  final String senderId;
  final String senderName;
  final String text;
  final DateTime timestamp;
  final bool isAutoGenerated;
  final List<int> pingPattern;
  final String? pollId; // 👈 add

  // 🆕 Optional fields for event messages
  final String? type; // 'event' | 'ping' | null
  final String? eventId;
  final String? eventName;
  final String? eventType;
  final DateTime? eventDateTime;
  final String? eventLocation;

  GroupMessageModel(
      {required this.id,
      required this.senderId,
      required this.senderName,
      required this.text,
      required this.timestamp,
      required this.isAutoGenerated,
      required this.pingPattern,
      this.type,
      this.eventId,
      this.eventName,
      this.eventType,
      this.eventDateTime,
      this.eventLocation,
      this.pollId});

  factory GroupMessageModel.fromFirestore(DocumentSnapshot doc) {
    final data = doc.data() as Map<String, dynamic>;

    return GroupMessageModel(
      id: doc.id,
      senderId: data['senderId'],
      senderName: data['senderName'] ?? '',
      text: data['text'] ?? '',
      timestamp: (data['timestamp'] != null && data['timestamp'] is Timestamp)
          ? (data['timestamp'] as Timestamp).toDate()
          : DateTime.now(),
      isAutoGenerated: data['isAutoGenerated'] ?? false,
      pingPattern: List<int>.from(data['pingPattern'] ?? []),

      // 🆕 Event fields (optional)
      type: data['type'],
      eventId: data['eventId'],
      eventName: data['eventName'],
      pollId: data['pollId'] as String?,
      eventType: data['eventType'],
      eventDateTime: data['eventDateTime'] is Timestamp
          ? (data['eventDateTime'] as Timestamp).toDate()
          : null,
      eventLocation: data['eventLocation'],
    );
  }

  Map<String, dynamic> toFirestore() {
    return {
      'senderId': senderId,
      'senderName': senderName,
      'text': text,
      'timestamp': Timestamp.fromDate(timestamp),
      'isAutoGenerated': isAutoGenerated,
      'pingPattern': pingPattern,

      // 🆕 Only add event fields if they're set
      if (type != null) 'type': type,
      if (eventId != null) 'eventId': eventId,
      if (eventName != null) 'eventName': eventName,
      if (eventType != null) 'eventType': eventType,
      if (eventDateTime != null)
        'eventDateTime': Timestamp.fromDate(eventDateTime!),
      if (eventLocation != null) 'eventLocation': eventLocation,

      // poll
      if (pollId != null) 'pollId': pollId,
    };
  }
}

// class GroupMessageModel {
//   final String id;
//   final String senderId;
//   final String senderName; // 👈 NEW
//   final String text;
//   final DateTime timestamp;
//   final bool isAutoGenerated;
//   final List<int> pingPattern;

//   GroupMessageModel({
//     required this.id,
//     required this.senderId,
//     required this.senderName,
//     required this.text,
//     required this.timestamp,
//     required this.isAutoGenerated,
//     required this.pingPattern,
//   });

//   factory GroupMessageModel.fromFirestore(DocumentSnapshot doc) {
//     final data = doc.data() as Map<String, dynamic>;

//     return GroupMessageModel(
//       id: doc.id,
//       senderId: data['senderId'],
//       senderName: data['senderName'] ?? '', // 👈 fallback
//       text: data['text'] ?? '',
//       timestamp: (data['timestamp'] != null && data['timestamp'] is Timestamp)
//           ? (data['timestamp'] as Timestamp).toDate()
//           : DateTime.now(),
//       isAutoGenerated: data['isAutoGenerated'] ?? false,
//       pingPattern: List<int>.from(data['pingPattern'] ?? []),
//     );
//   }

//   Map<String, dynamic> toFirestore() {
//     return {
//       'senderId': senderId,
//       'senderName': senderName,
//       'text': text,
//       'timestamp': Timestamp.fromDate(timestamp),
//       'isAutoGenerated': isAutoGenerated,
//       'pingPattern': pingPattern,
//     };
//   }
// }
