import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';

class GroupMessageModel {
  final String id;
  final String senderId;
  final String senderName; // 👈 NEW
  final String text;
  final DateTime timestamp;
  final bool isAutoGenerated;
  final List<int> pingPattern;

  GroupMessageModel({
    required this.id,
    required this.senderId,
    required this.senderName,
    required this.text,
    required this.timestamp,
    required this.isAutoGenerated,
    required this.pingPattern,
  });

  factory GroupMessageModel.fromFirestore(DocumentSnapshot doc) {
    final data = doc.data() as Map<String, dynamic>;

    return GroupMessageModel(
      id: doc.id,
      senderId: data['senderId'],
      senderName: data['senderName'] ?? '', // 👈 fallback
      text: data['text'] ?? '',
      timestamp: (data['timestamp'] != null && data['timestamp'] is Timestamp)
          ? (data['timestamp'] as Timestamp).toDate()
          : DateTime.now(),
      isAutoGenerated: data['isAutoGenerated'] ?? false,
      pingPattern: List<int>.from(data['pingPattern'] ?? []),
    );
  }

  Map<String, dynamic> toFirestore() {
    return {
      'senderId': senderId,
      'senderName': senderName,
      'text': text,
      'timestamp': Timestamp.fromDate(timestamp),
      'isAutoGenerated': isAutoGenerated,
      'pingPattern': pingPattern,
    };
  }
}
