import 'dart:developer';

import 'package:cloud_firestore/cloud_firestore.dart';

class MessageModel {
  final String id;
  final String senderId;
  final String text;
  final DateTime timestamp;
  final bool isAutoGenerated;
  final List<int> pingPattern;

  MessageModel({
    required this.id,
    required this.senderId,
    required this.text,
    required this.timestamp,
    required this.isAutoGenerated,
    required this.pingPattern,
  });

  // 🔹 Convert Firestore document to MessageModel
  factory MessageModel.fromFirestore(DocumentSnapshot doc) {
    final data = doc.data() as Map<String, dynamic>;

    // log('data : $data');

    return MessageModel(
      id: doc.id,
      senderId: data['senderId'],
      text: data['text'] ?? '',
      timestamp: (data['timestamp'] != null && data['timestamp'] is Timestamp)
          ? (data['timestamp'] as Timestamp).toDate() // ✅ Safe conversion
          : DateTime.now(),
      isAutoGenerated: data['isAutoGenerated'] ?? false,
      pingPattern: List<int>.from(data['pingPattern'] ?? []),
    );
  }

  // 🔹 Convert MessageModel to Firestore data
  Map<String, dynamic> toFirestore() {
    return {
      'senderId': senderId,
      'text': text,
      'timestamp': timestamp,
      'isAutoGenerated': isAutoGenerated,
      'pingPattern': pingPattern,
    };
  }
}
